name = "hakula-xyz-kiln"
compatibility_date = "2026-04-01"

routes = [{ pattern = "hakula.xyz", custom_domain = true }]
preview_urls = true

[assets]
directory = "./public"
not_found_handling = "404-page"

[observability.logs]
enabled = true

[env.dev]
routes = [{ pattern = "dev.hakula.xyz", custom_domain = true }]
